version: "3"

services:
  flask:
    build: ./flask
    container_name: flask
    volumes:
      - ./flask:/app
    ports:
      - 443:443
    restart: always
    command: python main.py
    depends_on:
      - postgres
  postgres:
    image: postgres
    hostname: localhost
    container_name: postgres
    ports:
        - 6543:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: dibotdb
    volumes:
        - postgres-test-data:/var/lib/postgresql/data
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
    postgres-test-data: