version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
    main_db:
        image: postgres
        hostname: localhost
        ports:
            - 6543:5432
        environment:
            POSTGRES_USER: hqduser
            POSTGRES_PASSWORD: hqdpassword
            POSTGRES_DB: hqddb
        volumes:
            - postgres-test-data:/var/lib/postgresql/data
        restart: always

    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    flask_server:
        build: ./flask_server/
        volumes:
            - ./flask_server:/app
        ports:
            - 5000:5000
        restart: always
        command: python app.py

volumes:
    postgres-test-data:
