version: '3'
services:
  flask_server:
    build:
      context: ""
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8443:8443
    restart: always
    command: python app.py
